apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-client
  labels:
    app.kubernetes.io/name: dex-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dex-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dex-client
    spec:
      containers:
        - name: dex-client
          image: alitari/dex-client:latest

          imagePullPolicy: "Always"
          ports:
            - name: callback
              containerPort: 5555