apiVersion: v1
kind: Service
metadata:
  name: dex-client
  labels:
    app.kubernetes.io/name: dex-client
spec:
  type: ClusterIP
  ports:
    - name: callback
      port: 5555
      targetPort: callback
  selector:
    app.kubernetes.io/name: dex-client