apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- "../base"

images:
- name: alitari/dex-client
  newName: alitari/dex-client-oidconsumer
  newTag: latest

nameSuffix: "-oidconsumer"
commonLabels:
  app.kubernetes.io/name: dex-client-oidconsumer

resources:
  - ingress.yaml

patchesStrategicMerge:
  - deploypatch.yaml