apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- "../base"

nameSuffix: "-v1"
commonLabels:
  app.kubernetes.io/name: dex-clientapp-v1

resources:
  - ingress.yaml

patchesStrategicMerge:
  - deploypatch.yaml