apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- "../base"
nameSuffix: "-1"
commonLabels:
  app.kubernetes.io/name: openldap-1

configMapGenerator:
- name: openldap
  files:
  - custom/01-default-users.ldif
