apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.4.0
          args:
            - --copy-service
            - --loglevel
            - debug
          imagePullPolicy: "Always"
          ports:
            - name: tcp-ldap
              containerPort: 389
          volumeMounts:
          - name: workdir
            mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
      initContainers:
        - name: openldap-init-ldif
          image: busybox
          command: ['sh', '-c', 'cp /customldif/* /workdir']
          imagePullPolicy: "Always"
          volumeMounts:
          - name: customldif
            mountPath: /customldif
          - name: workdir
            mountPath: /workdir
      volumes:
        - name: customldif
          configMap:
            name: openldap
        - name: workdir
          emptyDir: {}